name: Deploy Slackbot Service

on:
  push:
    paths:
      - 'slackbot/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Slackbot via SSH
        run: |
          bash scripts/deploy.sh slackbot python_script "C:\Services\slackbot" "Restart-Service slackbot-service"

