name: Deploy Techwise-Test Service

on:
  push:
    paths:
      - 'techwise-test/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Techwise-Test via SSH
        run: |
          bash scripts/deploy.sh techwise-test python "C:\Services\techwise-test" "Restart-Service techwise-service"

