name: Deploy Tesumi Service

on:
  push:
    paths:
      - 'tesumi/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Tesumi via SSH
        run: |
          bash scripts/deploy.sh tesumi docker "C:\\Services\\tesumi" "docker-compose restart"

